[[session]]
name = "Home ğŸ "
path = "~"

[[session]]
name = "Sesh"
path = "~/.config/sesh"

[[session]]
name = "Now Storyvine â¬›ï¸"
path = "/Users/albertobarboza/Dev/Repositories/Oakslab/Storyvine"

[[session]]
name = "LKSG ğŸš¢"
path = "~/Dev/Repositories/Osapiens/Bpt/lksg-backend"

[[session]]
name = "DMA E2E ğŸš¢"
path = "~/Dev/Repositories/Osapiens/Bpt/dma-e2e-tests"

[[session]]
name = "LKSG E2E ğŸš¢"
path = "~/Dev/Repositories/Osapiens/Bpt/e2e-tests"